### ISSUE TITLE
Fix World Save registering Better Questing

### ISSUE THREAD

**Issue by Emblin13** [CindyLouWho03/Rebirth-3#73]
When creating a new world, I'm only given the option to choose the world name. If I try to create a new world, forge says "there are 2 missing entries in this save", "questbook:itemquestbook" and "bq_standard:loot_chest". If I create the world anyways, it starts in creative mode with cheats disabled. Furthermore, the BQ quests are broken as every quest requirement is "betterquesting.placeholder". The FTB quests are also broken because the first quest, "Welcome to Yugospit", does not recognize the glacial precipitator in my inventory when I try to submit it.

Log file: https://www.dropbox.com/s/o5zgj9opseheaot/latest.log?dl=0

**Comment by CrankySupertoon01** [comment]
Sorry for late responce. Yes that is 100% intentional because we added FTB Quests and depreciated BQ

**Comment by Emblin13** [comment]
FTB Quests definitely does not seem to work for me. I even tried it again. Here is what I do:
1: Create new world
2: Grab the crescent hammer
3: Shift+rightclick both glacial precipitators
4: Open FTB Quests using the quest book
5: Click on "Welcome to Yugospit"
6: Click on the submit button which is under "tasks:"
7: Nothing happens.

Also, every new save still starts in creative mode with cheats disabled. The only way I can get into survival mode is if I open lan and set it to survival every time I load the save.

**Comment by CrankySupertoon01** [comment]
hmmm. I might just put it back to better questing when i have the chance
