### ISSUE TITLE
there's no recipe for luminous crafting table 

### ISSUE THREAD

**Issue by verticaljelly** [CindyLouWho03/Rebirth-3#94]

**Comment by CindyLouWho03** [comment]
You clearly haven’t used astral sorcery. Try reading the mods manual. In the next update I’m going to spawn an astral temple since I don’t think they are spawning

**Comment by verticaljelly** [comment]
mate, luminous crafting table needs to be craftable in the normal crafting table when illuminated by the rock crystals found in the temples that should theoretically spawn all over the world ... alternatively packs like sevtech ages allow it to be craftable through other means ... the Fosic resonator too as the Astral sorcery needs it for the other stuff. I'm ok with both having them spawn as well as the way that sevtech dealt with it ... I don't really care. 
Now that I think of that, because of the way this pack works like, I think that including blood magic to rush the game into night mode would be in order ;) and since you have the beneath ... well maybe add Abyssalcraft as well as a way of getting some serious bosses and threats to the game ... eventually betweenlands as well :O
